### ISSUE TITLE
VRC freezes

### ISSUE THREAD

**Issue by CyanTabby** [Astrum-Project/AstralUdonViewer#1]
When a world downloaded via VRCX is initializing for the first time VRChat freezes and causes unusual repeating clicking noises from system sounds until the VRChat process is killed

**Comment by xKiraiChan** [comment]
It's decompiling all of the UdonBehaviours on the map.
The beeping is to indicate that the process is still doing something and has not crashed.
If you wait long enough, it will completely decompile and save to the `UserData/AstralUdonViewer` folder

**Comment by CyanTabby** [comment]
I figured it was still trying to process something. It's never done that for me if the world wasn't predownloaded, and if I wait long enough I get the VRChat has stopped responding in-game pop-up and then an empty scene

**Comment by xKiraiChan** [comment]
It only runs once for a given map unless you delete the folder.
Depending on the size of that map it may take too long and you'll have to join it a second time.
When I figure out the problem with programs running corrupting the stack, ill be able to put it onto a button instead of on scene load, and ill make it multi-threaded or yielding.

**Comment by xKiraiChan** [comment]
I've made it deferred now, with 0b21dfe.
